name: Package Extension

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache apt packages
      uses: actions/cache@v4
      with:
        path: |
          /var/cache/apt
          /var/lib/apt
        key: ${{ runner.os }}-apt-${{ hashFiles('**/.github/workflows/package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Install GNOME dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gnome-shell \
          libglib2.0-dev \
          gettext \
          gnome-shell-extensions

    - name: Make package script executable
      run: chmod +x package.sh

    - name: Package extension
      run: ./package.sh <<< 'n'

    - name: Upload packaged extension
      uses: actions/upload-artifact@v4
      with:
        name: packaged-extension
        path: extension/*.zip
        retention-days: 30